# Generated by Django 3.2.25 on 2024-08-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admins.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='residency',
            constraint=models.UniqueConstraint(fields=('member', 'date'), name='unique_member_date'),
        ),
    ]
