# Generated by Django 3.2.25 on 2024-08-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('online_start_date', models.DateTimeField()),
                ('online_end_date', models.DateTimeField()),
                ('online_double_pts_end_date', models.DateTimeField()),
                ('folder_id', models.CharField(default=None, max_length=40, null=True)),
                ('parent_folder_id', models.CharField(max_length=40)),
                ('is_complete_online', models.BooleanField(default=False)),
                ('app_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admins.appinfo')),
            ],
        ),
    ]
